---
- name: Setup Minimal Swift
  hosts: aio 
  remote_user: root
  become: yes
  vars:
    bootstrap_host_loopback_swift_size: 1024
    # Set the data disk mount options.
    bootstrap_host_data_mount_options:
      machinectl: "noatime,nodiratime,compress=lzo,commit=120,{{ (ansible_kernel is version('4.5', '>=')) | ternary('space_cache=v2', 'space_cache') }}"
      zfs: "defaults"
      btrfs: "noatime,nodiratime,compress=lzo,commit=120,{{ (ansible_kernel is version('4.5', '>=')) | ternary('space_cache=v2', 'space_cache') }}"
      xfs: "noatime,nodiratime,logbufs=8,logbsize=256k"
      ext4: "noatime,nobh,barrier=0,data=writeback"
      dir: "defaults"
      lvm: "defaults"
      swap: "%%"
  tasks:

    - name: Create sparse Swift files
      command: "truncate -s {{ bootstrap_host_loopback_swift_size }}G /openstack/{{ item }}.img"
      args:
        creates: "/openstack/{{ item }}.img"
      with_items:
        - 'swift1'
        - 'swift2'
        - 'swift3'
      tags:
        - swift-file-create

    - name: Format the Swift files
      filesystem:
        fstype: xfs
        opts: "{{ bootstrap_host_format_options['xfs'] | default(omit) }}"
        dev: "/openstack/{{ item }}.img"
      with_items:
        - 'swift1'
        - 'swift2'
        - 'swift3'
      tags:
        - swift-format-file

    - name: Run the systemd mount role
      include_role:
        name: systemd_mount
      vars:
        systemd_mounts:
          - what: "/openstack/swift1.img"
            where: "/srv/swift1.img"
            options: "loop,{{ bootstrap_host_data_mount_options['xfs'] }}"
            type: "xfs"
            state: 'started'
            enabled: true
          - what: "/openstack/swift2.img"
            where: "/srv/swift2.img"
            options: "loop,{{ bootstrap_host_data_mount_options['xfs'] }}"
            type: "xfs"
            state: 'started'
            enabled: true
          - what: "/openstack/swift3.img"
            where: "/srv/swift3.img"
            options: "loop,{{ bootstrap_host_data_mount_options['xfs'] }}"
            type: "xfs"
            state: 'started'
            enabled: true
      tags:
        - swift-config
